# Generated by Django 2.1.5 on 2019-02-06 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('town', models.CharField(max_length=64)),
                ('estate', models.CharField(max_length=64)),
                ('street_and_hse_no', models.CharField(max_length=64)),
                ('duration_in', models.CharField(max_length=64)),
                ('rent_owned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('loan_no', models.IntegerField(default=0)),
                ('account_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('bank_code', models.IntegerField()),
                ('branch_code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('loan_no', models.IntegerField(default=0)),
                ('bsn_type', models.CharField(max_length=255)),
                ('business_income', models.IntegerField()),
                ('rental_income', models.IntegerField()),
                ('other_incomes', models.IntegerField()),
                ('years_of_operations', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('loan_no', models.IntegerField(default=0)),
                ('applicants_employer', models.CharField(max_length=64)),
                ('postal_address', models.CharField(max_length=160)),
                ('tel', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('staff_no', models.CharField(max_length=150)),
                ('employment_terms', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('physical_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoansApp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='LoanParticulars',
            fields=[
                ('loan_no', models.IntegerField(default=0)),
                ('loan_type', models.CharField(max_length=255)),
                ('purpose_of_loan', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherLoans',
            fields=[
                ('loan_no', models.IntegerField(default=0)),
                ('bank_name', models.CharField(max_length=255)),
                ('amount_advanced', models.IntegerField()),
                ('date_granted', models.DateField()),
                ('reapyment_period', models.IntegerField()),
                ('outstanding_balance', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalParticulars',
            fields=[
                ('loan_no', models.IntegerField(default=0)),
                ('membership_no', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(default='User', max_length=50)),
                ('last_name', models.CharField(default='User', max_length=50)),
                ('id_no', models.IntegerField()),
                ('dob', models.DateField(max_length=8)),
                ('address', models.CharField(max_length=100)),
                ('office_tel_no', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
                ('pin_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('no_of_dependents', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('physical_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoansApp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_path', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
