# Generated by Django 2.1.5 on 2019-02-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoansApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdetails',
            name='physical_address',
            field=models.CharField(max_length=160),
        ),
    ]
